"""
Covariance-Regularized SLSQP Blender / Meta-Learner for Stacking Ensembles.
Designed by: Decision Intelligence Architect
Target Audience: Ali Azizi (MSc Optimization, Sharif University of Technology)

This module implements a regularized Sequential Least Squares Programming (SLSQP)
constrained optimization blending class compatible with the Scikit-Learn API.
It solves the following optimization problem on Out-of-Fold (OOF) predictions:

    min_{w}  Loss(y_true, X * w) + lambda_1 * ||w||_2^2 + lambda_2 * (w^T * Sigma * w)
    subject to:
             sum(w_i) == 1
             w_i >= 0,  forall i

Where:
    - X: Out-of-fold probability predictions of shape (n_samples, n_models).
    - y_true: True binary targets of shape (n_samples,).
    - Sigma: Covariance matrix of base model prediction residuals (errors)
             to penalize co-volatility / correlated errors (Optimizer's Curse).
    - lambda_1 (l2_reg): L2 weight regularization penalty.
    - lambda_2 (cov_reg): Covariance regularization penalty.
"""

import numpy as np
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.metrics import log_loss, mean_squared_error
from scipy.optimize import minimize


class SLSQPBlender(BaseEstimator, ClassifierMixin):
    """
    Scikit-Learn compatible Meta-Learner utilizing Sequential Least Squares 
    Programming (SLSQP) to find optimal constrained blending weights.
    
    Includes Covariance Regularization to safeguard against the Optimizer's Curse 
    associated with small datasets (such as Kaggle Titanic).
    """
    def __init__(self, loss="logloss", l2_reg=0.01, cov_reg=0.05):
        """
        Parameters:
        -----------
        loss : str, default='logloss'
            The loss function to minimize. Supported values: 'logloss' (Binary Cross-Entropy)
            and 'mse' (Mean Squared Error / Brier Score).
        l2_reg : float, default=0.01
            Standard L2 weight regularization penalty parameter (lambda_1).
        cov_reg : float, default=0.05
            Covariance regularization penalty parameter (lambda_2) to minimize co-volatility.
        """
        self.loss = loss
        self.l2_reg = l2_reg
        self.cov_reg = cov_reg
        self.weights_ = None
        self.classes_ = np.array([0, 1])

    def fit(self, X, y):
        """
        Finds the optimal constrained blending weights.

        Parameters:
        -----------
        X : array-like of shape (n_samples, n_models)
            The probability predictions (OOF) generated by the base estimators.
        y : array-like of shape (n_samples,)
            True binary targets.
        """
        X = np.asarray(X)
        y = np.asarray(y)
        
        if X.ndim == 1:
            X = X.reshape(-1, 1)
            
        n_samples, n_models = X.shape

        # 1. Compute Residuals (Errors)
        # e_i = P_i - y_true
        residuals = X - y[:, np.newaxis]
        
        # 2. Compute the Residual Covariance Matrix (Sigma)
        if n_models > 1:
            cov_matrix = np.cov(residuals, rowvar=False)
        else:
            cov_matrix = np.array([[np.var(residuals)]])

        # 3. Define the Regularized Constrained Objective Function
        def objective_function(weights):
            # Compute the linear combination of predictions: P_blend = X * w
            blend_prob = np.dot(X, weights)
            # Clip probabilities to prevent log(0) numerical instability
            blend_prob = np.clip(blend_prob, 1e-15, 1.0 - 1e-15)

            # A. Base Loss Calculation
            if self.loss == "logloss":
                base_loss = log_loss(y, blend_prob)
            elif self.loss == "mse":
                base_loss = mean_squared_error(y, blend_prob)
            else:
                raise ValueError(f"Unsupported loss function: {self.loss}")

            # B. Regularization Term 1: Ridge (L2) Penalty
            l2_penalty = self.l2_reg * np.sum(weights ** 2)

            # C. Regularization Term 2: Covariance / Co-volatility Penalty
            # Penalizes models with correlated errors to enforce diversity
            cov_penalty = self.cov_reg * np.dot(weights.T, np.dot(cov_matrix, weights))

            return base_loss + l2_penalty + cov_penalty

        # 4. Set Constraints and Bounds
        # Constraint: sum(w_i) == 1
        constraints = {"type": "eq", "fun": lambda w: np.sum(w) - 1.0}
        
        # Bounds: 0 <= w_i <= 1 forall i
        bounds = [(0.0, 1.0) for _ in range(n_models)]

        # 5. Initialize Uniform Weights as starting point
        init_weights = np.ones(n_models) / n_models

        # 6. Run SLSQP Optimization
        res = minimize(
            objective_function,
            init_weights,
            method="SLSQP",
            bounds=bounds,
            constraints=constraints,
            options={"ftol": 1e-12, "maxiter": 1000}
        )

        if not res.success:
            import warnings
            warnings.warn(
                f"SLSQP optimization did not converge successfully: {res.message}. "
                "Falling back to uniform weights."
            )
            self.weights_ = init_weights
        else:
            self.weights_ = res.x

        return self

    def predict_proba(self, X):
        """
        Predict blended class probabilities.

        Parameters:
        -----------
        X : array-like of shape (n_samples, n_models)
            Base models' probability predictions.

        Returns:
        --------
        proba : ndarray of shape (n_samples, 2)
            Blended class probabilities.
        """
        X = np.asarray(X)
        if X.ndim == 1:
            X = X.reshape(-1, 1)
            
        prob_1 = np.dot(X, self.weights_)
        prob_1 = np.clip(prob_1, 0.0, 1.0)
        return np.column_stack((1.0 - prob_1, prob_1))

    def predict(self, X):
        """
        Predict binary classes.

        Parameters:
        -----------
        X : array-like of shape (n_samples, n_models)
            Base models' probability predictions.

        Returns:
        --------
        predictions : ndarray of shape (n_samples,)
            Binary class predictions (0 or 1).
        """
        proba = self.predict_proba(X)[:, 1]
        return (proba >= 0.5).astype(int)


# Simple smoke test and usage demonstration
if __name__ == "__main__":
    print("Executing SLSQPBlender validation test...")
    
    # Generate mock OOF predictions for 3 models
    np.random.seed(42)
    y_mock = np.random.binomial(1, 0.4, size=100)
    
    # Model 1: Good accuracy, slightly noisy
    p1 = np.clip(y_mock + np.random.normal(0, 0.2, size=100), 0, 1)
    # Model 2: Average accuracy
    p2 = np.clip(y_mock + np.random.normal(0, 0.3, size=100), 0, 1)
    # Model 3: Correlated with Model 2
    p3 = np.clip(p2 + np.random.normal(0, 0.1, size=100), 0, 1)
    
    X_mock = np.column_stack((p1, p2, p3))
    
    blender = SLSQPBlender(loss="logloss", l2_reg=0.01, cov_reg=0.1)
    blender.fit(X_mock, y_mock)
    
    print("\n[Validation Success]")
    print(f"Optimal Blending Weights: {blender.weights_}")
    print(f"Weight Sum: {np.sum(blender.weights_):.4f}")
    
    test_probs = blender.predict_proba(X_mock)[:5]
    print(f"Sample Blended Probabilities:\n{test_probs}")
